Repository CS2103-AY1819S2-W17-3/main, pull requests merged in 2019-02, with the labels that each got.

#20 Added colors for different tags (categories)
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High, status.Completed

#21 Updated Use Cases (Appendix C)
  docs/DeveloperGuide.adoc
Labels: document.Update

#25 Customised code to suit our product more
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.Enhancement
