Repository CS2103-AY1819S2-W17-3/main, pull requests merged in 2019-03, with the labels that each got.

#60 Dummy command `increase`
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/IncreaseCommand.java
  src/main/java/seedu/address/logic/commands/SpendCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/IncreaseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: needsReview, type.Enhancement

#63 Logic: `increase` command to accept parameters
  src/main/java/seedu/address/logic/commands/IncreaseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/IncreaseCommandParser.java
  src/test/java/seedu/address/logic/commands/IncreaseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/RecordUtil.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SpendCommandSystemTest.java
Labels: needsReview, type.Enhancement

#65 `Allocate` command & Changed App Icon + Title
  src/main/java/seedu/finance/logic/commands/AllocateCommand.java
  src/main/java/seedu/finance/logic/parser/AllocateCommandParser.java
  src/main/java/seedu/finance/logic/parser/FinanceTrackerParser.java
  src/main/java/seedu/finance/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/finance_tracker_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/finance/commons/util/AppUtilTest.java
  src/test/java/seedu/finance/logic/commands/AllocateCommandTest.java
  src/test/java/seedu/finance/logic/commands/IncreaseCommandTest.java
  src/test/java/seedu/finance/logic/parser/AllocateCommandParserTest.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
Labels: needsReview, type.Enhancement

#71 W9
  src/main/java/seedu/finance/logic/parser/CliSyntax.java
  src/main/java/seedu/finance/logic/parser/FinanceTrackerParser.java
  src/test/java/seedu/finance/logic/commands/AllocateCommandTest.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: needsReview, type.Enhancement

#73 Added more pre-defined colours for tags #20
  src/main/java/seedu/finance/model/util/SampleDataUtil.java
  src/main/java/seedu/finance/ui/RecordCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableFinanceTrackerTest/typicalRecordsFinanceTracker.json
  src/test/java/seedu/finance/logic/commands/SearchCommandTest.java
  src/test/java/seedu/finance/model/FinanceTrackerTest.java
  src/test/java/seedu/finance/model/ModelManagerTest.java
  src/test/java/seedu/finance/model/VersionedFinanceTrackerTest.java
  src/test/java/seedu/finance/model/record/RecordTest.java
  src/test/java/seedu/finance/model/record/UniqueRecordListTest.java
  src/test/java/seedu/finance/storage/JsonAdaptedRecordTest.java
  src/test/java/seedu/finance/storage/JsonFinanceTrackerStorageTest.java
  src/test/java/seedu/finance/testutil/TypicalRecords.java
  src/test/java/seedu/finance/ui/BrowserPanelTest.java
  src/test/java/seedu/finance/ui/StatusBarFooterTest.java
  src/test/java/seedu/finance/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/SpendCommandSystemTest.java
Labels: needsReview

#88 Wk9 ug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: needsReview

#92 Added dummy command for Summary feature
  src/main/java/seedu/finance/logic/commands/SummaryCommand.java
  src/main/java/seedu/finance/logic/parser/FinanceTrackerParser.java
  src/test/java/seedu/finance/logic/commands/SummaryCommandTest.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
Labels: document.Update, needsReview, status.onGoing, type.Enhancement

#93 Theme Switcher
  src/main/java/seedu/finance/ui/MainWindow.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PinkTheme.css
  src/main/resources/view/default.html
Labels: needsReview, type.Story

#90 Included a DateTimeFormatter formatter and LocalDate date
  docs/team/johndoe.adoc
  src/main/java/seedu/finance/model/record/Date.java
  src/main/java/seedu/finance/storage/JsonAdaptedRecord.java
  src/main/java/seedu/finance/ui/RecordCard.java
  src/test/java/guitests/guihandles/RecordCardHandle.java
  src/test/java/seedu/finance/model/record/DateTest.java
  src/test/java/seedu/finance/testutil/RecordUtil.java
  src/test/java/seedu/finance/ui/testutil/GuiTestAssert.java
Labels: needsReview, type.Task

#100 Reverse Feature
  src/main/java/seedu/finance/logic/commands/ReverseCommand.java
  src/main/java/seedu/finance/logic/parser/FinanceTrackerParser.java
  src/main/java/seedu/finance/model/FinanceTracker.java
  src/main/java/seedu/finance/model/Model.java
  src/main/java/seedu/finance/model/ModelManager.java
  src/main/java/seedu/finance/model/record/UniqueRecordList.java
  src/test/java/seedu/finance/logic/commands/ReverseCommandTest.java
  src/test/java/seedu/finance/logic/commands/SpendCommandTest.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
Labels: type.Task
