Repository CS2103-AY1819S2-W17-3/main, pull requests merged in 2019-04, with the labels that each got.

#104 Added d3.js files and files for graphPanel
  docs/GraphPage.html
  docs/stylesheets/js/d3.v3.min.js
  docs/stylesheets/js/draw.js
  src/main/java/seedu/finance/commons/core/LogsCenter.java
  src/main/java/seedu/finance/commons/events/BaseEvent.java
  src/main/java/seedu/finance/commons/events/ShowGraphRequestEvent.java
  src/main/java/seedu/finance/logic/commands/SummaryCommand.java
  src/main/java/seedu/finance/ui/GraphPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/style.css
  src/test/java/guitests/guihandles/GraphPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/finance/ui/GraphPanelTest.java
Labels: document.Update, needsReview, status.onGoing

#119 Allow duplicate records in spend command
  src/main/java/seedu/finance/logic/commands/EditCommand.java
  src/main/java/seedu/finance/logic/commands/SpendCommand.java
  src/main/java/seedu/finance/model/FinanceTracker.java
  src/main/java/seedu/finance/model/Model.java
  src/main/java/seedu/finance/model/record/UniqueRecordList.java
  src/test/java/seedu/finance/logic/commands/EditCommandTest.java
  src/test/java/seedu/finance/logic/commands/SpendCommandIntegrationTest.java
  src/test/java/seedu/finance/logic/commands/SpendCommandTest.java
  src/test/java/seedu/finance/model/FinanceTrackerTest.java
  src/test/java/seedu/finance/model/record/UniqueRecordListTest.java
Labels: needsReview, type.Enhancement

#121 Updated search command functionalities.
  src/main/java/seedu/finance/logic/commands/CommandFlag.java
  src/main/java/seedu/finance/logic/commands/SearchCommand.java
  src/main/java/seedu/finance/logic/commands/SortCommand.java
  src/main/java/seedu/finance/logic/parser/CliSyntax.java
  src/main/java/seedu/finance/logic/parser/SearchCommandParser.java
  src/main/java/seedu/finance/logic/parser/SortCommandParser.java
  src/main/java/seedu/finance/logic/parser/comparator/RecordAmountComparator.java
  src/main/java/seedu/finance/logic/parser/comparator/RecordCategoryComparator.java
  src/main/java/seedu/finance/logic/parser/comparator/RecordDateComparator.java
  src/main/java/seedu/finance/logic/parser/comparator/RecordNameComparator.java
  src/main/java/seedu/finance/model/FinanceTracker.java
  src/main/java/seedu/finance/model/record/DateContainsKeywordsPredicate.java
  src/test/java/seedu/finance/TestApp.java
  src/test/java/seedu/finance/logic/commands/SearchCommandTest.java
  src/test/java/seedu/finance/logic/commands/SortCommandTest.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
  src/test/java/seedu/finance/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/finance/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/finance/model/record/CategoryContainsKeywordsPredicateTest.java
  src/test/java/seedu/finance/model/record/DateContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FinanceTrackerSystemTest.java
  src/test/java/systemtests/ModelHelper.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: type.Enhancement

#125 Made updates to DG and PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/SummarySequenceDiagram.pptx
  docs/diagrams/SummarySequenceDiagram2.pptx
  docs/images/SummarySequenceDiagram.png
  docs/images/SummarySequenceDiagram2.png
  docs/team/geezlouisee.adoc
Labels: status.Completed

#127 DG: Updated reverse and sort features in Implementation section
  docs/DeveloperGuide.adoc
Labels: type.Task

#140 Minor edits & enhancements
  docs/UserGuide.adoc
  src/main/java/seedu/finance/logic/commands/SearchCommand.java
  src/main/java/seedu/finance/logic/commands/SortCommand.java
  src/main/java/seedu/finance/logic/parser/EditCommandParser.java
  src/main/java/seedu/finance/logic/parser/SearchCommandParser.java
  src/main/java/seedu/finance/logic/parser/comparator/RecordCategoryComparator.java
  src/main/java/seedu/finance/model/record/DateContainsKeywordsPredicate.java
  src/main/java/seedu/finance/model/record/Record.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
  src/test/java/seedu/finance/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/finance/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/finance/model/record/CategoryContainsKeywordsPredicateTest.java
  src/test/java/seedu/finance/model/record/DateContainsKeywordsPredicateTest.java
  src/test/java/seedu/finance/model/record/NameContainsKeywordsPredicateTest.java
Labels: type.Bug, type.Enhancement

#142 Enhance reverse command to allow -asc and -desc
  docs/UserGuide.adoc
  src/main/java/seedu/finance/logic/commands/SortCommand.java
  src/main/java/seedu/finance/logic/parser/CliSyntax.java
  src/main/java/seedu/finance/logic/parser/SortCommandParser.java
  src/test/java/seedu/finance/logic/commands/SortCommandTest.java
  src/test/java/seedu/finance/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement

#178 Week12 - More edits to SummaryCommand
  docs/UserGuide.adoc
  src/main/java/seedu/finance/MainApp.java
  src/main/java/seedu/finance/commons/core/ComponentManager.java
  src/main/java/seedu/finance/commons/core/EventsCenter.java
  src/main/java/seedu/finance/commons/events/ShowSummaryRequestEvent.java
  src/main/java/seedu/finance/commons/events/SwapBrowserPanelEvent.java
  src/main/java/seedu/finance/logic/Logic.java
  src/main/java/seedu/finance/logic/LogicManager.java
  src/main/java/seedu/finance/logic/commands/CommandResult.java
  src/main/java/seedu/finance/logic/commands/SummaryCommand.java
  src/main/java/seedu/finance/logic/parser/CliSyntax.java
  src/main/java/seedu/finance/logic/parser/FinanceTrackerParser.java
  src/main/java/seedu/finance/logic/parser/ParserUtil.java
  src/main/java/seedu/finance/logic/parser/SummaryCommandParser.java
  src/main/java/seedu/finance/model/Model.java
  src/main/java/seedu/finance/model/ModelManager.java
  src/main/java/seedu/finance/model/record/Date.java
  src/main/java/seedu/finance/ui/GraphPanel.java
  src/main/java/seedu/finance/ui/MainWindow.java
  src/main/java/seedu/finance/ui/SummaryPanel.java
  src/main/resources/view/BudgetPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SummaryPanel.fxml
  src/test/java/guitests/guihandles/GraphPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/SummaryPanelHandle.java
  src/test/java/guitests/guihandles/SummaryWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/finance/logic/commands/SpendCommandTest.java
  src/test/java/seedu/finance/logic/commands/SummaryCommandTest.java
  src/test/java/seedu/finance/logic/parser/FinanceTrackerParserTest.java
  src/test/java/seedu/finance/logic/parser/SummaryCommandParserTest.java
  src/test/java/seedu/finance/testutil/EventsUtil.java
  src/test/java/seedu/finance/ui/GraphPanelTest.java
  src/test/java/seedu/finance/ui/SummaryPanelTest.java
Labels: document.Update, priority.High, status.onGoing

#177 Working on system tests
  src/main/java/seedu/finance/logic/parser/SpendCommandParser.java
  src/main/java/seedu/finance/ui/RecordCard.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PinkTheme.css
  src/main/resources/view/RecordListCard.fxml
  src/test/java/guitests/guihandles/RecordCardHandle.java
  src/test/java/seedu/finance/TestApp.java
  src/test/java/seedu/finance/logic/commands/CommandTestUtil.java
  src/test/java/seedu/finance/logic/commands/IncreaseCommandTest.java
  src/test/java/seedu/finance/logic/parser/SpendCommandParserTest.java
  src/test/java/seedu/finance/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/ClockRule.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FinanceTrackerSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/SpendCommandSystemTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: needsReview, type.Task

#188 Updated graph colours
  src/main/java/seedu/finance/ui/SummaryPanel.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PinkTheme.css
Labels: type.Enhancement

#186 Added system tests for reverse and sort commands
  src/main/java/seedu/finance/logic/commands/ReverseCommand.java
  src/main/java/seedu/finance/logic/commands/SortCommand.java
  src/main/java/seedu/finance/logic/parser/SortCommandParser.java
  src/test/java/seedu/finance/logic/commands/ReverseCommandTest.java
  src/test/java/seedu/finance/logic/commands/SortCommandTest.java
  src/test/java/seedu/finance/logic/parser/SortCommandParserTest.java
  src/test/java/systemtests/ReverseCommandSystemTest.java
  src/test/java/systemtests/SortCommandSystemTest.java
Labels: needsReview, type.Task

#200 UG, DG updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ReverseSequenceDiagram.pptx
  docs/diagrams/SortSequenceDiagram.pptx
  docs/diagrams/sortExamples.pptx
  docs/images/reverseExample.png
  docs/images/sortExamples.png
  docs/images/sortNameDescExample.png
Labels: document.Update

#209 SetFile and Budget Tests
  src/main/java/seedu/finance/logic/commands/SetFileCommand.java
  src/main/java/seedu/finance/model/FinanceTracker.java
  src/main/java/seedu/finance/model/VersionedFinanceTracker.java
  src/main/java/seedu/finance/model/budget/Budget.java
  src/test/data/JsonSerializableFinanceTrackerTest/duplicateRecordFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/typicalRecordsFinanceTracker.json
  src/test/data/SetFileTest/invalidDataFile.json
  src/test/data/SetFileTest/validDataFile.json
  src/test/java/seedu/finance/logic/commands/SetFileCommandTest.java
  src/test/java/seedu/finance/logic/parser/SetFileCommandParserTest.java
  src/test/java/seedu/finance/model/budget/BudgetTest.java
  src/test/java/seedu/finance/model/record/AmountTest.java
Labels: priority.Medium, type.Task

#210 Updated ppp
  docs/images/in-credit-ble.png
  docs/team/kjiaxuan.adoc
Labels: document.Update

#208 Updated UG, DG and PPP
  docs/DeveloperGuide.adoc
  docs/GraphPage.html
  docs/UserGuide.adoc
  docs/diagrams/SummarySequenceDiagram.pptx
  docs/diagrams/SummarySequenceDiagram2.pptx
  docs/images/SummarySequenceDiagram.png
  docs/images/SummarySequenceDiagram2.png
  docs/images/summaryUI.png
  docs/images/summaryUI_2.png
  docs/stylesheets/js/d3.v3.min.js
  docs/stylesheets/js/draw.js
  docs/team/geezlouisee.adoc
  src/main/java/seedu/finance/commons/core/ComponentManager.java
  src/main/java/seedu/finance/commons/events/ShowSummaryRequestEvent.java
  src/main/java/seedu/finance/logic/commands/SummaryCommand.java
  src/main/java/seedu/finance/ui/MainWindow.java
  src/main/resources/view/style.css
Labels: document.Update, priority.High, status.onGoing

#216 Updated Developer Guide (Budget Set, Budget UI Update)
  docs/DeveloperGuide.adoc
  docs/diagrams/BudgetUiUpdateActivityDiagram.pptx
  docs/diagrams/SetSequenceDiagram.pptx
  docs/images/BudgetUiUpdateActivityDiagram.jpg
  docs/images/SetCommandSequenceDiagram.png
  docs/images/SetSequenceDiagram.jpg
  docs/team/JeremyLoye.adoc
  src/main/java/seedu/finance/model/FinanceTracker.java
Labels: document.Update, priority.High

#231 Added colours to ppp
  docs/team/kjiaxuan.adoc
Labels: document.Update

#242 Cleaned up some files
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/SummaryPanelHandle.java
  src/test/java/seedu/finance/logic/commands/SummaryCommandTest.java
  src/test/java/seedu/finance/logic/parser/SummaryCommandParserTest.java
  src/test/java/seedu/finance/testutil/EventsUtil.java
Labels: type.Task
